### PR TITLE
feat: add rest-api exercise

### PR DESCRIPTION
**Pull request by vaeng**
json with sqlite is hard. I have started this a while ago and have done a lot of different things in between. I have to confess, that I do not have a clean way to progress this exercise solution. The rest of the files is fine.

Does anyone want to write a solution and add their credit to the config.json file?

### CODE REVIEW

**Review by IsaacG — APPROVED** [review]
Does this need updating to match the new format?

It feels like a bit of a shame to coerce the one exercise that actually uses a DB into a JSON exercise.

**Comment by vaeng** [comment]
As it is not working yet, we can still change it to whatever we like it to be :)

**Comment by Steffan153** [comment]
Here's an example solution:

https://gist.github.com/Steffan153/89135660eadb6286b3e8f4b5f821d177


Also, the tests didn't account for different order of keys, so you might need something like this:

```sql
UPDATE tests
SET status = 'pass'
FROM (SELECT database, url, payload, result FROM 'rest-api') AS actual
WHERE (actual.database, actual.url, actual.payload) = (tests.database, tests.url, tests.payload)
AND (SELECT COUNT(*) FROM json_tree(actual.result) as a, json_tree(tests.expected) as b WHERE (a.fullkey, a.atom) IS (b.fullkey, b.atom)) =
    (SELECT COUNT(*) FROM json_tree(tests.expected))
AND (SELECT COUNT(*) FROM json_tree(tests.expected)) = (SELECT COUNT(*) FROM json_tree(actual.result));
```

**Comment by vaeng** [comment]
@Steffan153 
I think this fails as the version we aim for does not support the ->> syntax

**Comment by Steffan153** [comment]
The online test runner supports it, it's just the CI that's outdated. Maybe switch the action to Alpine? Ubuntu seems to be outdated

**Comment by Steffan153** [comment]
Welp, that's too bad. I've updated the gist to use `json_extract`.

**Comment by vaeng** [comment]
> Welp, that's too bad. I've updated the gist to use `json_extract`.

I can't see your new commit yet

**Comment by Steffan153** [comment]
I updated the gist: https://gist.github.com/Steffan153/89135660eadb6286b3e8f4b5f821d177

(I don't have write access for a commit)

**Pull request merged**
