### PR TITLE
Add track snippet

### PR DESCRIPTION
**Pull request by BNAndras**

### CODE REVIEW

**Review by vaeng — APPROVED** [review]
Simple. I like it. 

I think we have 6 lines or something.
Should we add something sqlite-like?
I don't have a good idea and it might turn away the regular SQL crowd.

**Review by IsaacG — APPROVED** [review]
Are we going to confuse people trying to solve Hello World?

**Comment by BNAndras** [comment]
Other tracks have hello world as their snippet. We can use something else though.On Feb 3, 2024, at 2:10 PM, Isaac Good ***@***.***> wrote:﻿
@IsaacG approved this pull request.

Are we going to confuse people trying to solve Hello World?

**Comment by glennj** [comment]
> Should we add something sqlite-like?

Perhaps a CREATE TABLE statement, and a `.save hello_world.db` ?

**Review by IsaacG — APPROVED** [review]

**Review by vaeng — APPROVED** [review]

**Pull request merged**
